name: MDVQuest
version: 1.2.5
main: com.mdvcraft.mdvquest.MDVQuestPlugin
api-version: '1.21'
author: MDVCRAFT
website: https://mdvcraft.xyz
softdepend:
  - MDVSocial
  - MDVRecetas
  - MDVHeadOres
  - MMOItems
  - MMOCore
  - MythicMobs
  - PlaceholderAPI
  - MDVClans
commands:
  mdvquest:
    description: Abre y administra las misiones rotativas.
    usage: /mdvquest
    aliases: [misiones, quests, quest]
permissions:
  mdvquest.use:
    description: Permite consultar y reclamar misiones.
    default: true
  mdvquest.admin:
    description: Permite recargar, administrar y reportar progreso manualmente.
    default: op
    children:
      mdvquest.editor: true
      mdvquest.admin.reroll: true
      mdvquest.admin.force: true
  mdvquest.editor:
    description: Permite usar el catálogo y editor visual de misiones sin comandos técnicos.
    default: op
  mdvquest.admin.reroll:
    description: Permite regenerar una o todas las rotaciones globales.
    default: op
  mdvquest.admin.force:
    description: Permite añadir una misión concreta a su rotación global actual sin borrar progreso.
    default: op
  mdvquest.access.vip1:
    description: Permite reclamar recompensas de instancias VIP1.
    default: false
  mdvquest.access.vip2:
    description: Permite reclamar recompensas de instancias VIP2.
    default: false
